version: '3.8'

services:
  muxlib-audioset:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Muxlib-Audioset
    environment:
      - TZ=Asia/Tokyo
      - JUPYTER_PORT=8888
      - JUPYTER_IP=0.0.0.0
      - JUPYTER_NOTEBOOK_DIR=/workspace/notebooks
      - PROJECT_NAME=Muxlib.Audioset
    volumes:
      - .:/workspace
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
