import torch


# for now, this code generated by github-copilot, Un tested yet
class AudioSetLabelEmbedder(torch.nn.Module):
    def __init__(self, embedding_size=128):
        super(AudioSetLabelEmbedder, self).__init__()
        self.embedding_size = embedding_size
        self.embedding = torch.nn.Embedding(527, self.embedding_size)

    def forward(self, x):
        return self.embedding(x)
